/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia2ej4;

import java.util.TreeSet;

/**
 *
 * @author Anto
 */
public class Supermercado extends javax.swing.JFrame {

    public static TreeSet<Producto> lista = new TreeSet ();
    public Supermercado() {
        initComponents();
        setLocationRelativeTo(null);
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuRubro = new javax.swing.JMenuItem();
        menuNombre = new javax.swing.JMenuItem();
        menuPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");

        jMenuItem1.setText("Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        menuRubro.setText("por Rubro");
        menuRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRubroActionPerformed(evt);
            }
        });
        jMenu2.add(menuRubro);

        menuNombre.setText("por Nombre");
        menuNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNombreActionPerformed(evt);
            }
        });
        jMenu2.add(menuNombre);

        menuPrecio.setText("por Precio");
        menuPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(menuPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        GestionProduc pr = new GestionProduc();
        pr.setVisible(true);
        Escritorio.add(pr);
        Escritorio.moveToFront(pr);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRubroActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        porRubro pr = new porRubro();
        pr.setVisible(true);
        Escritorio.add(pr);
        Escritorio.moveToFront(pr);
    }//GEN-LAST:event_menuRubroActionPerformed

    private void menuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNombreActionPerformed
       Escritorio.removeAll();
        Escritorio.repaint();
        porNombre pn = new porNombre();
        pn.setVisible(true);
        Escritorio.add(pn);
        Escritorio.moveToFront(pn);
    }//GEN-LAST:event_menuNombreActionPerformed

    private void menuPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrecioActionPerformed
        Escritorio.removeAll();
        Escritorio.repaint();
        porPrecio pp = new porPrecio();
        pp.setVisible(true);
        Escritorio.add(pp);
        Escritorio.moveToFront(pp);
    }//GEN-LAST:event_menuPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supermercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supermercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuNombre;
    private javax.swing.JMenuItem menuPrecio;
    private javax.swing.JMenuItem menuRubro;
    // End of variables declaration//GEN-END:variables

    private void cargarLista(){
        lista.add(new Producto(12,"Desodorante",150.6, 10, Rubro.PERFUMERIA));
        lista.add(new Producto(9,"Galletas",450.6, 30, Rubro.COMESTIBLE));
        lista.add(new Producto(10,"Lavandina",600.5, 20, Rubro.LIMPIEZA));
    }
}
